app:
    name :  My app
    description :  Welcome to ${app.name}

my:
    greeting :  Hello World
    list:
        values :  One, Two, Three

db:
    connection :  "{connectionString: 'http://___', userName: 'foo', password: 'pass'}"
    host :  127.0.0.1
    port :  8080

management.endpoints.web.exposure.include :  "*"

spring.config.import: optional:configserver:http://localhost:8888 

spring.application.name: spring-boot-config

